### PR TITLE
Upgrade for Symfony 5

### LINKED ISSUE #10: Upgrade for Symfony 5
Would you be interested in an upgrade to support Symfony 5?

### PR DESCRIPTION
**Pull request by gisostallenberg**
Allow to run the bundle in Symfony 3.4+, 4.3+ and 5.0+.

Closes #10.

### CODE REVIEW

**Comment by ivoba** [comment]
@gisostallenberg Thanks for the PR.
Looks good to me.
However removing PHP7.1 support is a breaking change.So we have to aim on v2.

Some linting is also failing. Here we have to add a ignore rule.
I can take of that before making the new release.

**Comment by gisostallenberg** [comment]
Why is removing 7.1 breaking? Users running PHP 7.1 will just get 1.4.0, which still works.

**Comment by gisostallenberg** [comment]
> Some linting is also failing. Here we have to add a ignore rule.

I just fixed that in 90e3479

**Comment by gisostallenberg** [comment]
@ivoba tests are passing :tada:

**Comment by gisostallenberg** [comment]
@ivoba could you merge and make sure https://packagist.org/packages/freshcells/soap-client-bundle is updated? In that case I will be able to better test the bundle before releasing 1.5.0

**Comment by ivoba** [comment]
@gisostallenberg Yes i agree on version 1.5.

I'll merge PR. Thanks for your efforts.

**Review by ivoba — APPROVED** [review]

**Comment by ivoba** [comment]
@gisostallenberg dev-master / 1.5.x-dev is on packagist.
Just ping me when all is fine in your tests and i tag release 1.5.0

**Comment by gisostallenberg** [comment]
Nice, thanks for your quick responses

**Comment by gisostallenberg** [comment]
@ivoba all is working as expected

**Comment by ivoba** [comment]
@gisostallenberg 1.5.0 was tagged and released.  

Thanks for the PR :+1:

**Pull request merged**
